import os
from decouple import config

APP_ENV = config('APP_ENV')
DATABASE_USERNAME = config('DATABASE_USERNAME')
DATABASE_PASSWORD = config('DATABASE_PASSWORD')
DATABASE_HOST = config('DATABASE_HOST')
DATABASE_NAME = config('DATABASE_NAME')
CONNECTION_STRING = config('CONNECTION_STRING')
JWT_SECRET = config('JWT_SECRET')
JWT_ALGORITHM = config('JWT_ALGORITHM')
JWT_EXPIRES_SECOND = int(config('JWT_EXPIRES_SECOND'))
